=== Joselu2099/LenguajeDeMarcas/TareasTema3/ejercicio4/ejercicio4.dtd
<!ELEMENT operaciones (operacion+)>
<!ELEMENT operacion (compra | venta)+>
<!ELEMENT compra (tituloscomprados)>
<!ELEMENT venta (titulosvendidos)>
    <!ELEMENT tituloscomprados (titulo, proveedor, fecha)>
    <!ELEMENT titulosvendidos (titulo, cantidad, entregado?, importe)>
        <!ELEMENT titulo (#PCDATA)>
        <!ELEMENT proveedor (#PCDATA)>
        <!ELEMENT fecha (dia, mes, año)>
            <!ELEMENT dia (#PCDATA)>
            <!ELEMENT mes (#PCDATA)>
            <!ELEMENT año (#PCDATA)>
        <!ELEMENT cantidad (#PCDATA)>
        <!ELEMENT entregado (#PCDATA)>
        <!ELEMENT importe (#PCDATA)>
            <!ATTLIST importe moneda CDATA #REQUIRED>

=== Joselu2099/LenguajeDeMarcas/TareasTema3/ejercicio4/ejercicio4.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE operaciones SYSTEM "ejercicio4.dtd">
<operaciones>
    <operacion>
        <compra>
            <tituloscomprados>  
                <titulo>Muñeca</titulo>
                <proveedor>Daniel Lopez</proveedor>
                <fecha>
                    <dia>1</dia>
                    <mes>12</mes>
                    <año>2022</año>
                </fecha>
            </tituloscomprados>
        </compra>
        <venta>
            <titulosvendidos>
                <titulo>Mascarillas</titulo>
                <cantidad>200</cantidad>
                <entregado>si</entregado>
                <importe moneda="$">100</importe>
            </titulosvendidos>
        </venta>
    </operacion>
    <operacion>
        <compra>
            <tituloscomprados>
            <titulo>Balón</titulo>
            <proveedor>Antonio Pacheco</proveedor>
            <fecha>
                <dia>5</dia>
                <mes>12</mes>
                <año>2022</año>
            </fecha>
            </tituloscomprados>
        </compra>
    </operacion>
</operaciones>
