=== Joselu2099/LenguajeDeMarcas/TareasTema3/ejercicio3/ejercicio3.dtd
<!ELEMENT listacursos (curso+)>
<!ELEMENT curso (alumno+)>
<!ELEMENT alumno (dni, nombre, ap1, ap2?, listaasignaturas)>
    <!ELEMENT dni (#PCDATA)>
    <!ELEMENT listaasignaturas (asignatura+)>
        <!ELEMENT asignatura (nombre, profesor)>
            <!ELEMENT profesor (nrp, nombre, ap1, ap2?)>
                <!ELEMENT nrp (#PCDATA)>
            <!ATTLIST asignatura codigo CDATA #REQUIRED>
    
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT ap1 (#PCDATA)>
    <!ELEMENT ap2 (#PCDATA)>

=== Joselu2099/LenguajeDeMarcas/TareasTema3/ejercicio3/ejercicio3.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE listacursos SYSTEM "ejercicio3.dtd">
<listacursos>
    <curso>
        <alumno>
            <dni>44e</dni>
            <nombre>Juan</nombre>
            <ap1>Sanchez</ap1>
            <listaasignaturas>
                <asignatura codigo="LM1">
                    <nombre>Leng marcas</nombre>
                    <profesor>
                        <nrp>8</nrp>
                        <nombre>Oscar</nombre>
                        <ap1>Gomez</ap1>
                    </profesor>
                </asignatura>
            </listaasignaturas>
        </alumno>
    </curso>
</listacursos>
