=== Joselu2099/LenguajeDeMarcas/TareasTema3/ejercicio1/ejercicio1.dtd
<!ELEMENT catalogo (producto)+>
<!ELEMENT producto (nombre, descripcion?, (origen | pais))>
    <!ATTLIST producto codigo ID #IMPLIED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT origen (#PCDATA)>

=== Joselu2099/LenguajeDeMarcas/TareasTema3/ejercicio1/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE catalogo SYSTEM "ejercicio1.dtd">
<catalogo>
    <producto>
        <nombre>Caja con autocierre</nombre>
        <descripcion>Caja de seguridad...</descripcion>
        <origen>Angola</origen>
    </producto>
    <producto codigo="jjjjj">
        <nombre>Caja llaves</nombre>
        <pais>Francia</pais>
    </producto>
</catalogo>
