=== Joselu2099/LenguajeDeMarcas/TareasTema3/ejercicio6/ejercicio6.dtd
<!ELEMENT aeropuerto (nombre, vuelos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT vuelos (vuelo+)>
<!ELEMENT vuelo (origen, destino, horasalida, horallegada, diario?)>
    <!ATTLIST vuelo codigo ID #REQUIRED>
    <!ATTLIST vuelo estado CDATA #REQUIRED>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT destino (#PCDATA)>
<!ELEMENT horasalida (#PCDATA)>
<!ELEMENT horallegada (#PCDATA)>
<!ELEMENT diario EMPTY>

=== Joselu2099/LenguajeDeMarcas/TareasTema3/ejercicio6/ejercicio6.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE aeropuerto SYSTEM "ejercicio6.dtd">
<aeropuerto>
    <nombre>Alicante</nombre>
    <vuelos>
        <vuelo codigo="CP9" estado="estrellado">
            <origen>Espa√±a</origen>
            <destino>Argentina</destino>
            <horasalida>11:00</horasalida>
            <horallegada>23:30</horallegada>       
        </vuelo>
        <vuelo codigo="CP0" estado="embarque">
            <origen>Madrid</origen>
            <destino>Barcelona</destino>
            <horasalida>13:00</horasalida>
            <horallegada>14:30</horallegada>
            <diario></diario>      
        </vuelo>
    </vuelos>
</aeropuerto>
